// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6ntUhhMA2GjAGX2WQJfajsgWmWOrR-kw',
    appId: '1:374374670661:web:8101832f1e3a7eefcede2c',
    messagingSenderId: '374374670661',
    projectId: 'taskflow-flutter-3b06a',
    authDomain: 'taskflow-flutter-3b06a.firebaseapp.com',
    storageBucket: 'taskflow-flutter-3b06a.firebasestorage.app',
    measurementId: 'G-M6XP53P3TH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSLxK9dS90xC7IozQRebKMtzmzg3UZhTM',
    appId: '1:374374670661:android:2b18e00a59ad5b44cede2c',
    messagingSenderId: '374374670661',
    projectId: 'taskflow-flutter-3b06a',
    storageBucket: 'taskflow-flutter-3b06a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkrMhtEaWXkiIJREkDSHLZ433T1uE4OH8',
    appId: '1:374374670661:ios:72feaaddd8169535cede2c',
    messagingSenderId: '374374670661',
    projectId: 'taskflow-flutter-3b06a',
    storageBucket: 'taskflow-flutter-3b06a.firebasestorage.app',
    iosBundleId: 'com.example.taskFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkrMhtEaWXkiIJREkDSHLZ433T1uE4OH8',
    appId: '1:374374670661:ios:72feaaddd8169535cede2c',
    messagingSenderId: '374374670661',
    projectId: 'taskflow-flutter-3b06a',
    storageBucket: 'taskflow-flutter-3b06a.firebasestorage.app',
    iosBundleId: 'com.example.taskFlow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6ntUhhMA2GjAGX2WQJfajsgWmWOrR-kw',
    appId: '1:374374670661:web:239e846637b6664dcede2c',
    messagingSenderId: '374374670661',
    projectId: 'taskflow-flutter-3b06a',
    authDomain: 'taskflow-flutter-3b06a.firebaseapp.com',
    storageBucket: 'taskflow-flutter-3b06a.firebasestorage.app',
    measurementId: 'G-0PSZ4MBX01',
  );
}
